### ISSUE TITLE
Can we have a struck out display instead of removing all the completed todos?

### ISSUE THREAD

**Issue by praveenscience** [Kakamotobi/todo-list-react#1]
I believe this will be working really good. And by this title, what I mean is:

![image](https://user-images.githubusercontent.com/1830380/143769184-b88adf70-543c-44bc-ba7f-c7fbbf548c9c.png)

I can work on this.

**Comment by Aditya-Narayan-Nayak** [comment]
Can I work On this feature?

**Comment by Kakamotobi** [comment]
Hey guys. Thanks for taking interest in my project. I've taken your feedback and decided to implement it myself. You can now check it on the live-site.

**Comment by praveenscience** [comment]
@Kakamotobi It's awesome.

**Comment by Kakamotobi** [comment]
@praveenscience Thank you!
